### ISSUE TITLE
Use instructions

### ISSUE THREAD

**Issue by kasnder** [MuntashirAkon/apksig-android#1]
Hello,

Is there any example code that explains how to use this library on Android?

**Comment by MuntashirAkon** [comment]
Well, Google doesn't officially provide any examples. But here's an example from my project: https://github.com/MuntashirAkon/AppManager/blob/b9b4add168020c6ae7a84c5c67138df6de2a3066/app/src/main/java/io/github/muntashirakon/AppManager/apk/signing/Signer.java

You only have to look that the `sign` and `verify` methods.
